server:
  port: 9084

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/notificationdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: order-events-exchange
    routing-key: order.created
    queue: notification.order-created-queue

logging:
  level:
    com.university.notificationservice: DEBUG
