server:
  port: 9083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest

catalog-service:
  url: http://localhost:9082

app:
  rabbitmq:
    exchange: order-events-exchange
    routing-key: order.created

logging:
  level:
    com.university.orderservice: DEBUG
